spring.application.name=entrecausas

spring.datasource.url=jdbc:mysql://localhost:3306/entrecausas
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Configuração para envio via Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Chave de criptografia AES para dados sensíveis (CPF e Telefone)
app.security.aes-key=${AES_KEY}

# Chave usada para gerar HMAC-SHA-256
app.security.hmac-key=${HMAC_KEY}

# Configuração de upload de arquivos
# Tamanho máximo permitido para um único arquivo enviado.
spring.servlet.multipart.max-file-size=5MB
# Tamanho máximo permitido para toda a requisição multipart.
spring.servlet.multipart.max-request-size=5MB